build: Dockerfile
	docker image build -t python:0.0.3 ~/Desktop/Workitems/myscripts/python/devops/Docker
build2: Dockerfile
	docker image build -t python:0.0.4 ~/Desktop/Workitems/myscripts/python/devops/Docker
images:buld
	docker images
run: build2
	docker run python:0.0.4
